zephyrproject-rtos/hal_stm32

- stm32cube/stm32mp1xx/README
- stm32cube/stm32mp1xx/drivers/include/stm32mp1xx_ll_ipcc.h
Add API to read the The IPCC peripheral HWCFGR register and return the
number of channels capability.
Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@st.com>
> ext: hal: add new API to get stm32 ipcc num of channel

- stm32cube/stm32mp1xx/README
- stm32cube/stm32mp1xx/drivers/include/stm32mp1xx_ll_spi.h
- stm32cube/stm32mp1xx/drivers/src/stm32mp1xx_ll_spi.c
- stm32cube/stm32mp1xx/soc/stm32mp151axx_cm4.h
- stm32cube/stm32mp1xx/soc/stm32mp151cxx_cm4.h
- stm32cube/stm32mp1xx/soc/stm32mp153axx_cm4.h
- stm32cube/stm32mp1xx/soc/stm32mp153cxx_cm4.h
- stm32cube/stm32mp1xx/soc/stm32mp157axx_cm4.h
- stm32cube/stm32mp1xx/soc/stm32mp157cxx_cm4.h
Update CMSIS registers definition related to SPI peripherals. 
Add SPI LL drivers to STM32CubeMP1.
SPI registers definition update should be part of next STM32CubeMP1 release (v1.1.0)
> stm32cube: stm32mp1x:  Add SPI LL

- stm32cube/CMakeLists.txt
Synchronize STM Cube HSE clock value with zephyr clock value by defining HSE_VALUE as the same value of CONFIG_CLOCK_STM32_HSE_CLOCK.
> HAL STM32: Synchronize STM Cube HSE clock value with zephyr clock value

- stm32cube/stm32l1xx/README
- stm32cube/stm32l1xx/soc/stm32l151xb.h
- stm32cube/stm32l1xx/soc/stm32l151xba.h
This is a bug in upstream CMSIS, but I don't have any contacts to get it
fixed there.
Signed-off-by: Karl Palsson <karlp@etactica.com>
> stm32l151xb: add missing SPI_CR2_FRF definitions

- stm32cube/stm32g4xx/README
- stm32cube/stm32g4xx/drivers/src/stm32g4xx_ll_utils.c
When configuring the PLL > 80MHz, an intermediate step is needed 
with AHB prescaler set to 2 before setting the actual value.
In case the actual value is AHB prescaler 1, it must be set, though.
This will fix https://github.com/zephyrproject-rtos/zephyr/issues/21715
> stm32cube: stm32g4xx: wrong clock setup

- scripts/make_stm32_module.py
- scripts/update_stm32_package.py
For stm32 series, get the version tree found on
https://github.com/STMicroelectronics/STM32Cube
and apply patches to update module to the latest version
run with `$ python ./scripts/update_stm32_package.py stm32xx`
> script: build new zephyr module from a new STM32Cube

- stm32cube/stm32g4xx/README
- stm32cube/stm32g4xx/drivers/src/stm32g4xx_ll_utils.c
- stm32cube/stm32l4xx/README
- stm32cube/stm32l4xx/drivers/src/stm32l4xx_ll_utils.c
set the AHB prescaler with correct value in case the pll
requires LL_RCC_SYSCLK_DIV_1 for HSE and HSI or MSI
This PR includes the https://github.com/zephyrproject-rtos/hal_stm32/pull/36
and applies the same fix to the STM32L4Rx and STM32L4Sx series
> stm32cube: stm32g4x and stm32l4Rx / stm32l4Sx: Fix SystemCoreClock value > 80MHz

- stm32cube/stm32g4xx/README
- stm32cube/stm32g4xx/drivers/src/stm32g4xx_ll_utils.c
SystemCoreClock value should be updated after AHB prescale
is set back to 1.
Signed-off-by: Richard Osterloh <richard.osterloh@gmail.com>
> stm32cube: stm32g4xx: Fix SystemCoreClock value > 80MHz

- CMakeLists.txt
- lib/CMakeLists.txt
Both modules ST and STM32 use the same HAS_STLIB Kconfig symbol.
This is not coherent, so rename the one used in stm32 module
as HAS_STM32LIB
> hal_stm32: rename HAS_STLIB in HAS_STM32LIB

- scripts/genpinctrl/genpinctrl.py
- scripts/tests/genpinctrl/conftest.py
- scripts/tests/genpinctrl/test_genpinctrl.py
Use pathlib facilities to improve path handling. Also added defaults to make it easier to use the script.
> scripts: genpinctrl: use pathlib

- scripts/README.rst
- scripts/update_stm32_package.py
When running ./update_stm32_package.py, script breaks due to
unexpected presence of common_ll/ under stm32cube/ .
Skip update when this directory is parsed.
Additionally, update README to avoid recurrent issue when using
the script.
> scripts: update_sm32_package: Fix issue with common_ll directory

- dts/st/f3/stm32f334c(4-6-8)tx-pinctrl.dtsi
- dts/st/f3/stm32f334c8yx-pinctrl.dtsi
- dts/st/f3/stm32f334k(4-6-8)tx-pinctrl.dtsi
- dts/st/f3/stm32f334k(4-6-8)ux-pinctrl.dtsi
- dts/st/f3/stm32f334r(6-8)tx-pinctrl.dtsi
- dts/st/g4/stm32g474c(b-c-e)tx-pinctrl.dtsi
- dts/st/g4/stm32g474c(b-c-e)ux-pinctrl.dtsi
- dts/st/g4/stm32g474m(b-c-e)tx-pinctrl.dtsi
- dts/st/g4/stm32g474meyx-pinctrl.dtsi
- dts/st/g4/stm32g474p(b-c-e)ix-pinctrl.dtsi
- dts/st/g4/stm32g474q(b-c-e)tx-pinctrl.dtsi
- dts/st/g4/stm32g474r(b-c-e)tx-pinctrl.dtsi
- dts/st/g4/stm32g474v(b-c-e)hx-pinctrl.dtsi
- dts/st/g4/stm32g474v(b-c-e)ix-pinctrl.dtsi
- dts/st/g4/stm32g474v(b-c-e)tx-pinctrl.dtsi
- dts/st/g4/stm32g484cetx-pinctrl.dtsi
- dts/st/g4/stm32g484ceux-pinctrl.dtsi
- dts/st/g4/stm32g484metx-pinctrl.dtsi
- dts/st/g4/stm32g484meyx-pinctrl.dtsi
- dts/st/g4/stm32g484peix-pinctrl.dtsi
- dts/st/g4/stm32g484qetx-pinctrl.dtsi
- dts/st/g4/stm32g484retx-pinctrl.dtsi
- dts/st/g4/stm32g484vehx-pinctrl.dtsi
- dts/st/g4/stm32g484veix-pinctrl.dtsi
- dts/st/g4/stm32g484vetx-pinctrl.dtsi
- scripts/genpinctrl/stm32-pinctrl-config.yaml
Add options for high-resolution timer HRTIM to pinctrl-config and generate new pinctrl DTS files.
I know that the HRTIM peripheral is not yet supported by Zephyr, but I'm working on a driver and would like to use the pinctrl properly already.
> dts: add HRTIM pinctrl

- stm32cube/stm32f0xx/drivers/include/stm32_assert.h
- stm32cube/stm32f1xx/drivers/include/stm32_assert.h
- stm32cube/stm32f2xx/drivers/include/stm32_assert.h
- stm32cube/stm32f3xx/drivers/include/stm32_assert.h
- stm32cube/stm32f4xx/drivers/include/stm32_assert.h
- stm32cube/stm32f7xx/drivers/include/stm32_assert.h
- stm32cube/stm32g0xx/drivers/include/stm32_assert.h
- stm32cube/stm32g4xx/drivers/include/stm32_assert.h
- stm32cube/stm32h7xx/drivers/include/stm32_assert.h
- stm32cube/stm32l0xx/drivers/include/stm32_assert.h
- stm32cube/stm32l1xx/drivers/include/stm32_assert.h
- stm32cube/stm32l4xx/drivers/include/stm32_assert.h
- stm32cube/stm32l5xx/drivers/include/stm32_assert.h
- stm32cube/stm32mp1xx/drivers/include/stm32_assert.h
- stm32cube/stm32wbxx/drivers/include/stm32_assert.h
- stm32cube/stm32wlxx/drivers/include/stm32_assert.h
This commit fixes the build issues due to incorrect usage of "#" as
a beginning of comments in stm32_assert.h on all series, hence "#"
is replaced by C style comments.
Signed-off-by: Krishna Mohan Dani <krishnamohan.d@hcl.com>
> asserts: stm32: Fixes build issues when asserts are enabled

- scripts/serie_update.py
- scripts/stm32_assert_template.txt
scripts: serie_update: manage stm32_assert.h file
Remove useless stm32_assert_template.h
create stm32_assert.h thanks to Jinja2 template
Script automation corresponding to https://github.com/zephyrproject-rtos/hal_stm32/pull/100
> scripts: serie_update: manage stm32_assert.h file

- stm32cube/stm32wlxx/README
- stm32cube/stm32wlxx/drivers/src/stm32wlxx_ll_utils.c
HSE prescaler value is not taken into account when computing
PLL frequency using HSE as input clock.
Fix this.
> stm32cube/wl: ll_utils: Consider HSEPRE when configuring PLL using HSE

- stm32cube/stm32f4xx/README
- stm32cube/stm32f4xx/drivers/src/stm32f4xx_hal_qspi.c
An unused variable was declared in HAL_QSPI_Command_IT.
Remove it.
An internal ST bug was created to fix this.
> stm32cube: stm32f4: Remove unused variable

- stm32cube/stm32u5xx/LICENSE.md
- stm32cube/stm32u5xx/drivers/include/stm32u5xx_hal_conf.h
- stm32cube/stm32u5xx/drivers/include/stm32u5xx_ll_rcc.h
The BSD 3-Clause LICENSE file provided in this commit matches
the LICENSE file referred to in files extracted from STM32CubeU5
package under directory stm32cube/stm32u5xx.
> stm32cube: u5: Add License file for the whole directory

- stm32cube/stm32u5xx/drivers/include/stm32_assert.h
The comment in the
modules/hal/stm32/stm32cube/stm32u5xx/drivers/include/stm32_assert.h
is not well formatted.
> stm32cube: u5: correct the header file of the stm32_assert.h

- stm32cube/stm32h7xx/README
- stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_eth.c
Ethernet HAL configures interrupts to be received upon filling every
RX descriptor. When timestamping is enabled, application needs to
process both normal and context descriptors, but there is a race
condition in HAL_ETH_IsRxDataAvailable() that might miss context
descriptor, effectively leaking it.
This change introduces spinlock to wait for context descriptor if
normal context indicates it will be available.
Signed-off-by: Alex Sergeev <asergeev@carbonrobotics.com>
> stm32cube: stm32h7: eth: avoid descriptor leak with enabled timestamping

- stm32cube/stm32u5xx/README
- stm32cube/stm32u5xx/drivers/src/stm32u5xx_ll_utils.c
These definitions were suspicious
Fix them.
Internal issue: 116963
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/42228
> stm32cube/stm32u5: ll_utils.c: Fix UTILS_SCALE_... definitions

- stm32cube/stm32wlxx/drivers/src/stm32wlxx_ll_utils.c
The __LL_RCC_CALC_MSI_FREQ expects MSISEL param to be
LL_RCC_MSIRANGESEL_STANDBY or LL_RCC_MSIRANGESEL_RUN
which is not the value that  LL_RCC_MSI_IsEnabledRangeSelect returns.
The return code from LL_RCC_MSI_IsEnabledRangeSelect is 1 or 0 and the parameter of the __LL_RCC_CALC_MSI_FREQ
is expected to be LL_RCC_MSIRANGESEL_STANDBY or LL_RCC_MSIRANGESEL_RUN
Because of wrong MSIRangeTable entry, the calculated **pllrfreq** is not the right value
> stm32WL gives the right parameter to LL __LL_RCC_CALC_MSI_FREQ

- stm32cube/stm32wlxx/README
add the text to the README 
after merge of the
https://github.com/zephyrproject-rtos/hal_stm32/pull/133/
> update README for the stm32wl after changing LL_PLL_ConfigSystemClock_MSI

- .github/workflows/test.yml
- scripts/requirements-test.txt
- scripts/requirements.txt
Allow for more flexibility when it comes to dependencies. The scripts do
not have any strong dependency or known compatibility issues, so do not
specify any version. This means the latest version will be downloaded.
If anything comes up, scripts can always be updated or versions until
scripts are updated.
Update Python versions tested on CI as well.
> scripts: dependencies: do not specify any version and update tested Python versions

- stm32cube/stm32u5xx/README
- stm32cube/stm32u5xx/drivers/include/Legacy/stm32_hal_legacy.h
Align U5 LL_PWR_EnableVDDIO2 function name to name used on other STM32 series: LL_PWR_EnableVddIO2
Apply similar treatment to:
- LL_PWR_DisableVDDUSB
- LL_PWR_EnableVDDIO2
- LL_PWR_DisableVDDIO2
> stm32cube: u5: Rename LL_PWR_EnableVDDIO2 to LL_PWR_EnableVddIO2

- stm32cube/stm32h7xx/README
- stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_eth.c
drivers: STM32H7: ethernet: PTP clock doesn’t works
fix to the V2 HAL API to get PTP to work
In the HAL_ETH_ReadData function where it checks for the last descriptor, I added a checked if the TSA bit was set in DESC1
If the TSA bit is set then have a peak at the context descriptor which should be the one after the last descriptor
If the CTXT bit is set in the context descriptor then extract the timestamps
> PTP ETH_STM32_HAL_API_V2

- stm32cube/stm32c0xx/README
Not that significant but I made a copy-paste misstake when fixing the last comment of [# 161](https://github.com/zephyrproject-rtos/hal_stm32/pull/161).
> stm32cubec0xx: Correct patch list in readme

- stm32cube/stm32h7xx/README
- stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_eth.c
Read timestamp only when status flag is set in Tx descriptor. Fire transmit timestamp callbacks only when there is a valid non-zero timestamp.
> stm32cube: stm32h7: use transmit timestamp status flag.

- stm32cube/stm32h5xx/README
- stm32cube/stm32h5xx/drivers/src/stm32h5xx_hal_eth.c
fix to the HAL_API_V2 to get PTP to work
In the HAL_ETH_ReadData function where it checks for the last descriptor, I added a checked if the TSA bit was set in DESC1
If the TSA bit is set then have a peak at the context descriptor which should be the one after the last
descriptor
If the CTXT bit is set in the context descriptor then extract the timestamps
update README to fix to the V2 HAL API to get PTP to work
> stm32cube: stm32h5:  ethernet: PTP clock doesn’t works

- stm32cube/stm32h5xx/README
- stm32cube/stm32h5xx/drivers/include/stm32h5xx_hal_dcache.h
- stm32cube/stm32h5xx/drivers/include/stm32h5xx_hal_sai.h
- stm32cube/stm32h5xx/drivers/include/stm32h5xx_ll_dlyb.h
The stm32h503 soc does not embed delayblock (DLYB) or SAI block or DCACHE instances.
Consequently the corresponding drivers should be included.
> Stm32h503  does not enable the driver if instance is not present

- scripts/serie_update.py
STM32Cube HAL drivers are now included as Git submodules in the upstream STM32Cube repositories. So we need additional commands to fetch them.
For "git clone", we need to add --recursive or "--recurse-submodules".
For "git fetch", if it's the 1st time the local Cube directories are updated after the change in the upstream repositories, "git submodule update --init" is needed to specifically fetch the HAL Drivers submodules.
> scripts: serie_update: add Git commands to fetch HAL Drivers Git submodules

- scripts/serie_update.py
This reverts commit 818cef7f16ea0a2cb211ae3de06ea8a1e0d0da1a.
Changes introduced in this commit (PR #182) are not enough to update Cube packages correctly following the introduction of submodules in the upstream STM32Cube repos.
> Revert "scripts: serie_update: fetch submodules"

- scripts/ble_library.py
- scripts/serie_update.py
STM32Cube HAL & CMSIS Device drivers are now included as Git submodules in the upstream STM32Cube repos. So we need to use additional or different Git commands to fetch them & integrate the changes correctly:
- To clone STM32Cube repos with the submodules, we add the "--recursive" option to "git clone".
- Instead of using "git reset --hard" to clean the working tree and switch to a given tag, which misses with submodules in various ways, we use "git checkout -f --recurse-submodules". "Using --recurse-submodules will update the content of all active submodules according to the commit recorded in the superproject. If local modifications in a submodule would be overwritten the checkout will fail unless -f is used." https://git-scm.com/docs/git-checkout
> scripts: serie_update: integration of changes in Git submodules of HAL & CMSIS Device drivers

- stm32cube/stm32u5xx/drivers/include/stm32u5xx_hal_nand.h
- stm32cube/stm32u5xx/drivers/include/stm32u5xx_hal_nor.h
- stm32cube/stm32u5xx/drivers/include/stm32u5xx_hal_sram.h
- stm32cube/stm32u5xx/drivers/include/stm32u5xx_ll_fmc.h
This set of minor patches to the STM32CubeU5 files is necessary to support building for the STM32U545 chip.  These changes have been provided to ST (https://github.com/STMicroelectronics/STM32CubeU5/issues/41). However, they have fixed the issue internally and are awaiting a future release to push them out.
I am in the process of creating a PR for Zephyr-proper to add support for the STM32U545 part as well as the Nucleo-U545RE-Q board.  That PR is dependent on these changes.
> fix header inclusion on stm32u545 parts

- stm32cube/CMakeLists.txt
These headers provide redirections from legacy symbols definitions. They are provided only for backward compatibility, but in context of Zephyr integration we're supposed to update stm32 drivers to stay up to date with latest versions ath using deprecated symbols.
Purely remove the inclusion and update symbols used in Zephyr if required.
As a benefit this should minimize the possibility of conflicts with Zephyr or other subsystems API (such as POSIX).
> stm32cube: Remove legacy headers inclusion

- LICENSE
This repo LICENSE file was missing:
- reference to SLA0044 used for STM32WBA binary blobs
- reference to Apache 2.0 Licnese used for dts files
Additionally, clarify the wording about the BSD-3-Clause license used for files extracted from STM32Cube packages and the location of the impacted files.
> LICENSE: Complete and clarify

- lib/stm32wba/hci/README
- lib/stm32wba/hci/app_conf.h
Extended advertising option is enabled in CFG_BLE_OPTIONS
> lib/stm32wba/hci: Enabling extended advertising

- stm32cube/stm32h5xx/README
- stm32cube/stm32h5xx/soc/stm32h503xx.h
This is a mistake in CMSIS header file, since SAU is not present on STM32H503 devices
> stm32cube: soc: Set __SAUREGION_PRESENT to 0 for STM32H503

- CMakeLists.txt
- ble_fw_mkbox/CMakeLists.txt
- zephyr/blobs/boards/license.md
- zephyr/module.yml
Configure zephyr/module.yaml to allow importation of BLE controller-only firmware required to work with zephyr bluetooth stack. Also, add in ./CMakeLists.txt the include file generation from the blob.
blobs request to TSC is [here](https://github.com/zephyrproject-rtos/zephyr/issues/74326)
> add ble f/w blobs for STEVAL-MKBOXPRO board

- zephyr/module.yml
Field `name` is missing in module.yml file.
Fix this.
> zephyr: module.yml: Add missing module name

- .github/workflows/test.yml
Remove Python 3.7 and 3.8 from the CI test matrix, as these versions are deprecated (3.8 goes EOL in October 2024) / EOL (since June 27th 2023 for 3.7).
This enables usage of Python 3.9+ features in scripts, such as str.removeprefix/str.removesuffix (as done in #225).
There should not be any issue caused by this since the scripts are always executed manually anyways.
> ci: don't test on deprecated python versions

- scripts/genpinctrl/genpinctrl.py
This PR adds three new features to the `genpinctrl` script to improve QoL, notably when introducing new series or regenerating pinctrl for new signals:
* graceful handling of non-Git pin data folders
* If the pin data folder is not a git repository, script no longer crashes when generating the README file 
* support family filtering for (re)generation
* In allowlist mode, pinctrl is generated only for specified families 
* In forbidlist mode, pinctrl is generated for all families except those specified
* __N.B.: when filtering is active, unlike in "default" mode, existing pinctrl files are not deleted__
* automatically detect the XML namespace from pin data files
* Script will now attempt to detect the correct XMLNS from one file of the corpus
* Files sourced from other places that the …
> Add various enhancements to genpinctrl script

- .github/workflows/test.yml
upload-artifact@v2 action is deprecated - update to v4 to fix CI
> ci: update upload-artifact action to v4

- stm32cube/stm32f7xx/README
- stm32cube/stm32f7xx/drivers/src/stm32f7xx_hal_eth.c
This fix ensures that the TX timestamp is properly set by correctly
checking the ETH_DMATXDESC_LS and ETH_DMATXDESC_TTSS flags in the DESCO register.
Fixes https://github.com/STMicroelectronics/STM32CubeF7/issues/121
> STM32f7: Fix TX timestamp check 

- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/config/ble_full/ll_fw_config.h
Update the license terms to fit Synopsys MIT license as updated by them
> lib: stm32wba: Update license terms of ll_fw_config.h

- dts/st/n6/stm32n645a0hxq-pinctrl.dtsi
- dts/st/n6/stm32n645b0hxq-pinctrl.dtsi
- dts/st/n6/stm32n645i0hxq-pinctrl.dtsi
- dts/st/n6/stm32n645l0hxq-pinctrl.dtsi
- dts/st/n6/stm32n645x0hxq-pinctrl.dtsi
- dts/st/n6/stm32n647a0hxq-pinctrl.dtsi
- dts/st/n6/stm32n647b0hxq-pinctrl.dtsi
- dts/st/n6/stm32n647l0hxq-pinctrl.dtsi
- dts/st/n6/stm32n647x0hxq-pinctrl.dtsi
- dts/st/n6/stm32n655a0hxq-pinctrl.dtsi
- dts/st/n6/stm32n655b0hxq-pinctrl.dtsi
- dts/st/n6/stm32n655i0hxq-pinctrl.dtsi
- dts/st/n6/stm32n655l0hxq-pinctrl.dtsi
- dts/st/n6/stm32n655x0hxq-pinctrl.dtsi
- dts/st/n6/stm32n657a0hxq-pinctrl.dtsi
- dts/st/n6/stm32n657b0hxq-pinctrl.dtsi
- dts/st/n6/stm32n657i0hxq-pinctrl.dtsi
- dts/st/n6/stm32n657l0hxq-pinctrl.dtsi
- dts/st/n6/stm32n657x0hxq-pinctrl.dtsi
- scripts/genpinctrl/stm32-pinctrl-config.yaml
Correct pinctrl config of the ethernet RGMII
Add missing pinctrl ETH1_RGMII_TX_CTL and ETH1_RGMII_CLK125
> STM32N6 Ethernet : Add missing rgmii pinctrl 

- lib/stm32wba/BLE_TransparentMode/STM32_WPAN/Target/linklayer_plat.c
Migrate LINKLAYER_PLAT_EnableRadioIT, LINKLAYER_PLAT_DisableRadioIT, LINKLAYER_PLAT_EnableIRQ and LINKLAYER_PLAT_DisableIRQ to zephyr repo
> lib: stm32wba: linklayer_plat: Migrate some functions to zephyr repo

- lib/stm32wba/CMakeLists.txt
Remove the check of Nucleo WBA52CG in the CMakeList and remove its support in Zephyr.
> lib: stm32wba: Remove support of Nucleo WBA52CG board

- stm32cube/stm32h7rsxx/README
- stm32cube/stm32h7rsxx/soc/stm32h7s7xx.h
All SoCs of this series support SMPS, so defning this symbol, as it is done on stm32h7 series is not required.
> stm32cube: stm32h7rs: SMPS is de facto supported

- dts/st/u5/stm32u599bjyxq-pinctrl.dtsi
- dts/st/u5/stm32u599nihxq-pinctrl.dtsi
- dts/st/u5/stm32u599njhxq-pinctrl.dtsi
- dts/st/u5/stm32u5a9bjyxq-pinctrl.dtsi
- dts/st/u5/stm32u5a9njhxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9bjyxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9njhxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9vitxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9vjtxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9zijxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9zitxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9zjjxq-pinctrl.dtsi
- dts/st/u5/stm32u5f9zjtxq-pinctrl.dtsi
- dts/st/u5/stm32u5g9bjyxq-pinctrl.dtsi
- dts/st/u5/stm32u5g9njhxq-pinctrl.dtsi
- dts/st/u5/stm32u5g9vjtxq-pinctrl.dtsi
- dts/st/u5/stm32u5g9zjjxq-pinctrl.dtsi
- dts/st/u5/stm32u5g9zjtxq-pinctrl.dtsi
- scripts/genpinctrl/stm32-pinctrl-config.yaml
For HSPI DQS pins could be numbered 0 or 1. Take it into account in the pinctrl-config script and generate a new batch of -pinctrl.dtsi files
> dts: Generate dqs0 and dqs1 signals

- lib/stm32wb0/BLE_TransparentMode/STM32_BLE/Target/bleplat.c
- lib/stm32wb0/README.rst
Call appropriate Zephyr function for using TRNG peripheral with BLE library.
Modify README to include the new changes.
Supplementary [PR#90018](https://github.com/zephyrproject-rtos/zephyr/pull/90018)
> lib: stm32wb0: Call appropriate Zephyr function for using TRNG peripheral

- lib/stm32wba/BLE_TransparentMode/STM32_WPAN/Target/linklayer_plat.c
- lib/stm32wba/STM32_WPAN/link_layer/ll_sys/inc/linklayer_plat.h
Use Zephyr function `stm32_backup_domain_enable_access()` and `stm32_backup_domain_disable_access()` to enable/disable access to LSE configuration registers under back domain access protection instead of raw access. These functions have a reference counter for access requests to ensure access remains enabled when other component require it.
> lib: stm32wba: use reference count for backup domain accesses

- LICENSE
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/config/ble_full/ll_fw_config.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/_40nm_reg_files/DWC_ble154combo.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/bsp.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/common_types.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/event_manager.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/evnt_schdlr_gnrc_if.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/hci.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/ll_intf.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/ll_intf_cmn.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/mem_intf.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/os_wrapper.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/power_table.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/pta.h
Add Synopsys MIT license terms
> license: Add Synopsys MIT license terms

- stm32cube/stm32h7xx/README
- stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_ospi.c
The source and destination addresses in the HAL_MDMA_Start_IT call were swapped, causing incorrect data transfers. The data buffer (pData) should be the source, and the OSPI data register (DR) should be the destination. This commit fixes the argument order to ensure proper data transmission via DMA.
fixes: #94350
> stm32cube: stm32h7xx: drivers: Correct DMA source and destination addresses

- lib/stm32wba/BLE_TransparentMode/Core/Inc/app_conf.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/config/ble_full/ll_fw_config.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/bsp.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/common_types.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/event_manager.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/evnt_schdlr_gnrc_if.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/hci.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/ll_intf.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/ll_intf_cmn.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/mem_intf.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/os_wrapper.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/power_table.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_cmd_lib/inc/pta.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_sys/inc/linklayer_plat.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_sys/inc/ll_sys.h
- lib/stm32wba/STM32_WPAN/link_layer/ll_sys/src/ll_sys_dp_slp.c
- lib/stm32wba/Utilities/tim_serv/stm32_timer.h
some header files and system files of the Link Layer in zephyr are not aligned with the header file and system files of the Link Layer in STM32Cube_FW_WBA Release 1.6.0
> lib: stm32wba: Fix Link Layer and LE integration on STM32WBA

- stm32cube/stm32h7rsxx/README
- stm32cube/stm32h7rsxx/drivers/src/stm32h7rsxx_hal_dcmipp.c
- stm32cube/stm32mp13xx/README
- stm32cube/stm32mp13xx/drivers/src/stm32mp13xx_hal_dcmipp.c
- stm32cube/stm32mp2xx/README
- stm32cube/stm32mp2xx/drivers/src/stm32mp2xx_hal_dcmipp.c
- stm32cube/stm32n6xx/README
- stm32cube/stm32n6xx/drivers/src/stm32n6xx_hal_dcmipp.c
Allow to call HAL_DCMIPP_PIPE_SetConfig when the pipe state is READY. Currently it is only possible to use this function if the pipe state is RESET and ERROR states.
Indeed, it is possible to reconfigure the PIPE as soon as the pipe is not currently being used, aka in the READY state. With that done, it becomes possible to change the PIPE configuration between two use-cases without having to DeInit / Init the HAL_DCMIPP or use the unitary pixel packer functions.
> dcmipp: allow PIPE_SetConfig when pipe state is READY

- dts/README.rst
- dts/st/u3/stm32u385rgtxq-pinctrl.dtsi
This PR adds some missing SAI1 signals.
We observed that the STM32U385RGTxQ.xml file (https://github.com/STMicroelectronics/STM32_open_pin_data/blob/master/mcu/STM32U385RGTxQ.xml) contains only one pin definition. However, the Nucleo U385RG Q datasheet (https://www.st.com/resource/en/datasheet/stm32u385cg.pdf, page 85) shows additional signals available on AF13.
Currently, there is not enough time to investigate other U3_*.xml files or create an issue in the STM32_open_pin_data repository.
These changes are required to resolve issues encountered in the I2S sample ( https://github.com/zephyrproject-rtos/zephyr/pull/94082)
> dts: st: u3: stm32u385rgtxq:  add missing sa1_fs_a pins

- zephyr/module.yml
This PR is dedicated to update URL address for WBA6_LinkLayer_Thread_lib_Zephyr.a and WBA6_LinkLayer15_4_Zephyr.a libraries
> lib: blobs: change url for stm32wba Link Layer libraries
